'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {addPhotos,allPhotos,deletePhoto,deleteReportPhotos,PhotoRecord,photosFor,updatePhoto} from './storage';

type Status='draft'|'open'|'closed';
type Report={id:string;status:Status;obra:string;local:string;data:string;clima:string;servicos:string;ocorrencias:string;efetivo:string;equipamentos:string;observacoes:string;createdAt:string;updatedAt:string;log:{event:string;at:string}[]};
const KEY='rdo-facil-v2-reports',DRAFT='rdo-facil-v2-draft';
const blank=():Report=>({id:crypto.randomUUID(),status:'draft',obra:'',local:'',data:new Date().toISOString().slice(0,10),clima:'Ensolarado',servicos:'',ocorrencias:'',efetivo:'',equipamentos:'',observacoes:'',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),log:[]});
const loadReports=():Report[]=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
const dateBR=(date:string)=>date?new Date(date+'T12:00:00').toLocaleDateString('pt-BR'):'—';
const listOf=(value:string)=>value.trim()?value.split(/\n+/).map(line=>line.trim().replace(/^[*•-]\s*/, '')).filter(Boolean).map(line=>`• ${line}`).join('\n'):'—';
const textOf=(r:Report)=>`RELATÓRIO DIÁRIO DE OBRA\n\nObra: ${r.obra||'—'}\nLocal: ${r.local||'—'}\nData: ${dateBR(r.data)}\nCondição do tempo: ${r.clima||'—'}\n\nSERVIÇOS EXECUTADOS\n${listOf(r.servicos)}\n\nOCORRÊNCIAS\n${r.ocorrencias||'Sem ocorrências.'}\n\nEQUIPAMENTOS UTILIZADOS\n${r.equipamentos||'—'}\n\nOBSERVAÇÕES\n${r.observacoes||'—'}\n\nEFETIVO\n${listOf(r.efetivo)}`;

export default function Home(){
 const [reports,setReports]=useState<Report[]>([]),[report,setReport]=useState<Report>(blank),[photos,setPhotos]=useState<PhotoRecord[]>([]),[tab,setTab]=useState<'dados'|'fotos'>('dados'),[history,setHistory]=useState(false),[preview,setPreview]=useState(false),[notice,setNotice]=useState(''),[selected,setSelected]=useState<string[]>([]),[quickService,setQuickService]=useState('');
 const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{const migrated=migrateLegacy(loadReports());setReports(migrated);localStorage.setItem(KEY,JSON.stringify(migrated));try{const d=localStorage.getItem(DRAFT)||localStorage.getItem('rdo-facil-rascunho');if(d){const raw=JSON.parse(d);setReport(normalizeLegacy(raw,'draft'))}}catch{};if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js').then(reg=>reg.update()).catch(()=>{});const refresh=()=>{if(!sessionStorage.getItem('rdo-sw-refreshed')){sessionStorage.setItem('rdo-sw-refreshed','1');location.reload()}};navigator.serviceWorker.addEventListener('controllerchange',refresh);return()=>navigator.serviceWorker.removeEventListener('controllerchange',refresh)}},[]);
 useEffect(()=>{photosFor(report.id).then(setPhotos)},[report.id]);
 useEffect(()=>{if(report.status==='draft')localStorage.setItem(DRAFT,JSON.stringify(report))},[report]);
 const filled=useMemo(()=>[report.obra,report.local,report.servicos].filter(v=>v.trim()).length,[report]);
 const update=(key:keyof Report,value:string)=>{if(report.status==='closed')return;setReport(r=>({...r,[key]:value,updatedAt:new Date().toISOString()}))};
 const flash=(text:string)=>{setNotice(text);setTimeout(()=>setNotice(''),2300)};
 const persist=(event:string,status?:Status,base=report)=>{const now=new Date().toISOString();const resolved=status||(base.status==='draft'?'open':base.status);const next={...base,status:resolved,updatedAt:now,log:[...base.log,{event,at:now}]};const items=[next,...reports.filter(r=>r.id!==next.id)].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));setReport(next);setReports(items);localStorage.setItem(KEY,JSON.stringify(items));localStorage.removeItem(DRAFT);flash(event);return next};
 const fresh=()=>{setReport(blank());setSelected([]);setTab('dados');setHistory(false);scrollTo({top:0,behavior:'smooth'})};
 const openReport=(r:Report)=>{setReport(r);setHistory(false);setSelected([]);scrollTo({top:0,behavior:'smooth'})};
 async function filesChosen(files:FileList|null){if(!files?.length)return;await addPhotos(report.id,[...files]);setPhotos(await photosFor(report.id));flash(`${files.length} foto(s) adicionada(s)`);if(input.current)input.current.value=''}
 async function removePhoto(id:string){if(!confirm('Excluir esta foto do aparelho?'))return;await deletePhoto(id);setPhotos(await photosFor(report.id));setSelected(s=>s.filter(x=>x!==id))}
 async function share(withPhotos=true){const chosen=photos.filter(p=>!withPhotos?false:!selected.length||selected.includes(p.id));const files=chosen.map((p,i)=>new File([p.blob],p.name||`rdo-foto-${i+1}.jpg`,{type:p.type}));const data:ShareData={title:`RDO — ${report.obra}`,text:textOf(report)};if(files.length&&navigator.canShare?.({files}))data.files=files;try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(textOf(report));open('https://wa.me/?text='+encodeURIComponent(textOf(report)),'_blank');flash('Texto copiado para compartilhar')}}catch(e){if((e as Error).name!=='AbortError')flash('Não foi possível compartilhar as fotos neste aparelho')}}
 function addQuickService(){const value=quickService.trim().replace(/^[*•-]\s*/,'');if(!value)return;const next={...report,servicos:report.servicos.trim()?`${report.servicos.trim()}\n• ${value}`:`• ${value}`,updatedAt:new Date().toISOString()};setQuickService('');setReport(next);if(report.status==='open')persist('Serviço executado adicionado','open',next);else flash('Serviço acrescentado ao rascunho')}
 async function copyText(){await navigator.clipboard.writeText(textOf(report));flash('Texto do RDO copiado')}
 function whatsapp(){open('https://wa.me/?text='+encodeURIComponent(textOf(report)),'_blank','noopener,noreferrer')}
 async function removeReport(id:string){if(!confirm('Excluir este RDO e todas as fotos dele?'))return;await deleteReportPhotos(id);const items=reports.filter(r=>r.id!==id);setReports(items);localStorage.setItem(KEY,JSON.stringify(items));if(report.id===id)fresh()}
 async function backup(){const ps=await allPhotos();const encoded=await Promise.all(ps.map(async p=>({...p,blob:await blobToData(p.blob)})));download(JSON.stringify({version:2,exportedAt:new Date().toISOString(),reports,photos:encoded},null,2),`rdo-facil-backup-${new Date().toISOString().slice(0,10)}.json`,'application/json')}
 async function restore(file:File){try{const data=JSON.parse(await file.text());if(!Array.isArray(data.reports))throw Error();for(const p of data.photos||[]){const res=await fetch(p.blob);await updatePhoto({...p,blob:await res.blob()})}setReports(data.reports);localStorage.setItem(KEY,JSON.stringify(data.reports));flash('Backup restaurado com sucesso')}catch{flash('Arquivo de backup inválido')}}
 const title=report.status==='draft'?'Novo relatório':report.obra||'RDO';
 return <main className="appShell">
  <header className="appHeader"><button className="brand bare" onClick={fresh}><span className="brandMark">R</span><span><strong>RDO Fácil</strong><small>Diário de obra</small></span></button><div className="headerActions"><button className="historyButton" onClick={()=>setHistory(true)}>Histórico <b>{reports.length}</b></button><button className="newButton" onClick={fresh}>+ Novo RDO</button></div></header>
  {notice&&<div className="toast">{notice}</div>}
  <section className="intro"><div><p className="eyebrow">{report.status==='closed'?'RDO CONCLUÍDO':report.status==='open'?'RDO EM ANDAMENTO':'REGISTRO DE CAMPO'}</p><h1>{title}</h1><p>{report.status==='closed'?'Registro bloqueado para edição. Reabra se precisar corrigir.':'Documente o dia da obra com clareza, mesmo sem internet.'}</p></div><div className="draftBadge"><i/> {report.status==='draft'?'Rascunho salvo neste aparelho':`Atualizado em ${new Date(report.updatedAt).toLocaleString('pt-BR')}`}</div></section>
  <div className="workspace"><section className="editorCard"><div className="tabs"><button className={tab==='dados'?'active':''} onClick={()=>setTab('dados')}>Dados do RDO</button><button className={tab==='fotos'?'active':''} onClick={()=>setTab('fotos')}>Fotos <span>{photos.length}</span></button></div>
   {tab==='dados'?<fieldset disabled={report.status==='closed'} className="formBody">
    <Section number="01" title="Identificação" help="Onde e quando o serviço aconteceu"><div className="grid two"><Field label="Nome da obra *" value={report.obra} onChange={v=>update('obra',v)} placeholder="Ex.: Residencial Jardim Sul"/><Field label="Local / trecho *" value={report.local} onChange={v=>update('local',v)} placeholder="Rua, bloco, pavimento ou estaca"/><Field label="Data" type="date" value={report.data} onChange={v=>update('data',v)}/><label>Condição do tempo<select value={report.clima} onChange={e=>update('clima',e.target.value)}><option>Ensolarado</option><option>Nublado</option><option>Chuva leve</option><option>Chuva intensa</option><option>Tempo instável</option></select></label></div></Section>
    <Section number="02" title="Produção do dia" help="Registre o avanço e os acontecimentos"><Area label="Serviços executados *" value={report.servicos} onChange={v=>update('servicos',v)} placeholder="Descreva serviços, quantidades e trechos executados..."/><label>Lançamento rápido de serviço<div className="quickService"><input value={quickService} onChange={e=>setQuickService(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addQuickService()}}} placeholder="Digite uma pequena atualização da obra..."/><button type="button" onClick={addQuickService}>Lançar serviço</button></div><small className="fieldHelp">Cada lançamento entra como um novo tópico no relatório.</small></label><Area label="Ocorrências" value={report.ocorrencias} onChange={v=>update('ocorrencias',v)} placeholder="Imprevistos, paralisações ou interferências..."/><div className="quick"><span>Inserir:</span><button type="button" onClick={()=>update('ocorrencias','Condições climáticas adversas (chuva) impactaram a execução dos serviços, devido ao acúmulo de água e à saturação do solo na área de trabalho.')}>Chuva</button><button type="button" onClick={()=>update('ocorrencias','Interferência em ligação de água de residência durante a execução dos serviços, corrigida no local mediante emenda da tubulação.')}>Ligação de água</button><button type="button" onClick={()=>update('ocorrencias','Não foram registradas ocorrências no período.')}>Sem ocorrências</button></div></Section>
    <Section number="03" title="Recursos e fechamento" help="Equipe, equipamentos e observações"><Area label="Efetivo" value={report.efetivo} onChange={v=>update('efetivo',v)} placeholder="Ex.: 1 encarregado, 2 oficiais, 3 ajudantes"/><div className="grid two"><Area label="Equipamentos utilizados" value={report.equipamentos} onChange={v=>update('equipamentos',v)} placeholder="Máquinas, veículos e ferramentas..."/><Area label="Observações" value={report.observacoes} onChange={v=>update('observacoes',v)} placeholder="Pendências e próximos passos..."/></div></Section>
   </fieldset>:<div className="photoPanel">{!photos.length?<div className="photoEmpty"><div className="cameraMark">+</div><h2>Fotos deste RDO</h2><p>As imagens ficam na galeria e nunca entram no PDF.</p></div>:<><div className="galleryTop"><div><h2>Galeria da obra</h2><p>Toque para selecionar fotos para compartilhar.</p></div><button onClick={()=>input.current?.click()}>+ Adicionar</button></div><div className="gallery">{photos.map(photo=><article className={'photoCard '+(selected.includes(photo.id)?'selected':'')} key={photo.id}><button className="photoSelect" onClick={()=>setSelected(s=>s.includes(photo.id)?s.filter(x=>x!==photo.id):[...s,photo.id])}><img src={URL.createObjectURL(photo.blob)} alt={photo.caption||'Foto da obra'}/><span>{selected.includes(photo.id)?'✓':''}</span></button><input aria-label="Legenda da foto" placeholder="Adicionar legenda..." value={photo.caption} onChange={e=>{const next={...photo,caption:e.target.value};setPhotos(ps=>ps.map(p=>p.id===photo.id?next:p));updatePhoto(next)}}/><button className="deletePhoto" onClick={()=>removePhoto(photo.id)}>Excluir</button></article>)}</div></>}<input ref={input} hidden type="file" accept="image/*" multiple onChange={e=>filesChosen(e.target.files)}/><button className="addPhotos" onClick={()=>input.current?.click()}>{photos.length?'Adicionar mais fotos':'Adicionar fotos'}</button><small>As fotos são armazenadas somente neste aparelho.</small></div>}
  </section>
  <aside className="sidePanel"><div className="progressCard"><div className="progressTop"><div><small>PREENCHIMENTO</small><strong>{filled}/3 essenciais</strong></div><span>{Math.round(filled/3*100)}%</span></div><div className="progress"><i style={{width:`${filled/3*100}%`}}/></div><p>{filled===3?'Tudo pronto para salvar o RDO.':'Informe obra, local e serviços executados.'}</p></div><div className="livePreview"><div><small>PRÉ-VISUALIZAÇÃO AO VIVO</small><b>{report.status==='closed'?'Concluído':report.status==='open'?'Em andamento':'Rascunho'}</b></div><pre>{textOf(report)}</pre></div><div className="actionsCard"><h2>Seu relatório</h2><p>PDF limpo e fotos sempre em uma galeria separada.</p>{report.status==='draft'?<button className="primaryButton" disabled={filled<3} onClick={()=>persist('RDO aberto')}>Abrir RDO do dia</button>:report.status==='open'?<><button className="primaryButton" onClick={()=>persist('Alterações salvas')}>Salvar alterações</button><button className="secondaryButton" onClick={()=>persist('RDO concluído','closed')}>Concluir RDO</button></>:<button className="primaryButton" onClick={()=>persist('RDO reaberto','open')}>Reabrir RDO</button>}<button className="secondaryButton" disabled={report.status==='draft'} onClick={()=>setPreview(true)}>Visualizar / PDF</button><button className="secondaryButton" onClick={copyText}>Copiar texto</button><button className="secondaryButton" onClick={whatsapp}>Enviar por WhatsApp</button><button className="secondaryButton" disabled={report.status==='draft'||!photos.length} onClick={()=>share(true)}>Compartilhar RDO + fotos</button><div className="localNote"><span>✓</span><div><strong>Privado por padrão</strong><small>Dados e fotos ficam neste aparelho.</small></div></div></div></aside></div>
  {history&&<div className="modalBackdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setHistory(false)}}><section className="historyPanel"><header><div><p className="eyebrow">ARQUIVO LOCAL</p><h2>Histórico de RDOs</h2></div><button onClick={()=>setHistory(false)}>×</button></header><div className="historyTools"><button onClick={backup}>Fazer backup</button><label className="restore">Restaurar backup<input hidden type="file" accept=".json" onChange={e=>e.target.files?.[0]&&restore(e.target.files[0])}/></label></div>{!reports.length?<div className="emptyHistory">Nenhum RDO salvo ainda.</div>:<div className="historyList">{reports.map(r=><article key={r.id}><div className="historyInfo"><strong>{r.obra||'Obra não informada'}</strong><small>{dateBR(r.data)} · {r.local||'Local não informado'}</small><span className={'status '+r.status}>{r.status==='closed'?'Concluído':'Em andamento'}</span>{r.log?.length>0&&<details><summary>Consultar log ({r.log.length})</summary><ul>{[...r.log].reverse().map((item,i)=><li key={i}>{new Date(item.at).toLocaleString('pt-BR')} — {item.event}</li>)}</ul></details>}</div><div><button onClick={()=>openReport(r)}>Abrir</button><button onClick={()=>{setReport({...r,id:crypto.randomUUID(),status:'draft',log:[],createdAt:new Date().toISOString()});setHistory(false)}}>Duplicar</button><button className="danger" onClick={()=>removeReport(r.id)}>Excluir</button></div></article>)}</div>}</section></div>}
  {preview&&<div className="modalBackdrop reportBackdrop"><section className="reportModal"><div className="reportToolbar"><button onClick={()=>setPreview(false)}>Fechar</button><button onClick={()=>window.print()}>Salvar como PDF / Imprimir</button></div><article className="printReport"><header><div><p>RELATÓRIO DIÁRIO DE OBRA</p><h2>{report.obra||'RDO Fácil'}</h2></div><b>RDO</b></header><dl><div><dt>Obra</dt><dd>{report.obra||'—'}</dd></div><div><dt>Local / trecho</dt><dd>{report.local||'—'}</dd></div><div><dt>Data</dt><dd>{dateBR(report.data)}</dd></div><div><dt>Tempo</dt><dd>{report.clima||'—'}</dd></div></dl>{[['Serviços executados',report.servicos],['Ocorrências',report.ocorrencias||'Sem ocorrências.'],['Efetivo',report.efetivo],['Equipamentos utilizados',report.equipamentos],['Observações',report.observacoes]].map(([a,b])=><section key={a}><h3>{a}</h3><p>{b||'—'}</p></section>)}<footer>Gerado pelo RDO Fácil em {new Date().toLocaleString('pt-BR')} · Fotos disponíveis somente na galeria do aplicativo.</footer></article></section></div>}
 </main>
}
function Section({number,title,help,children}:{number:string;title:string;help:string;children:React.ReactNode}){return <section className="formSection"><div className="sectionHeading"><span>{number}</span><div><h2>{title}</h2><p>{help}</p></div></div>{children}</section>}
function Field({label,value,onChange,placeholder,type='text'}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;type?:string}){return <label>{label}<input type={type} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function Area({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string}){return <label>{label}<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></label>}
function download(content:string,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function blobToData(blob:Blob):Promise<string>{return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(reader.error);reader.readAsDataURL(blob)})}
function normalizeLegacy(raw:Record<string,unknown>,forced?:Status):Report{const now=new Date().toISOString();return{id:String(raw.id||crypto.randomUUID()),status:forced||(raw.status==='closed'?'closed':raw.status==='open'?'open':'draft'),obra:String(raw.obra||''),local:String(raw.local||''),data:String(raw.data||new Date().toISOString().slice(0,10)),clima:String(raw.clima||'Ensolarado'),servicos:String(raw.servicos||''),ocorrencias:String(raw.ocorrencias||''),efetivo:String(raw.efetivo||raw.equipe||''),equipamentos:String(raw.equipamentos||''),observacoes:String(raw.observacoes||''),createdAt:String(raw.createdAt||raw.updatedAt||now),updatedAt:String(raw.updatedAt||now),log:Array.isArray(raw.log)?raw.log as Report['log']:[]}}
function migrateLegacy(current:Report[]){try{const old=JSON.parse(localStorage.getItem('rdo-facil-historico')||'[]') as Record<string,unknown>[];const ids=new Set(current.map(r=>r.id));const recovered=old.map(r=>normalizeLegacy(r)).filter(r=>!ids.has(r.id));if(recovered.length)localStorage.setItem('rdo-facil-v2-migrated','true');return[...current,...recovered].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt))}catch{return current}}
