export type PhotoRecord={id:string;reportId:string;name:string;type:string;createdAt:string;caption:string;blob:Blob};
const DB='rdo-facil-db', STORE='photos';
function database():Promise<IDBDatabase>{return new Promise((resolve,reject)=>{const request=indexedDB.open(DB,1);request.onupgradeneeded=()=>{const db=request.result;if(!db.objectStoreNames.contains(STORE)){const store=db.createObjectStore(STORE,{keyPath:'id'});store.createIndex('reportId','reportId')}};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function photosFor(reportId:string):Promise<PhotoRecord[]>{const db=await database();return new Promise((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).index('reportId').getAll(reportId);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
export async function addPhotos(reportId:string,files:File[]){const db=await database();const tx=db.transaction(STORE,'readwrite');for(const file of files)tx.objectStore(STORE).put({id:crypto.randomUUID(),reportId,name:file.name,type:file.type||'image/jpeg',createdAt:new Date().toISOString(),caption:'',blob:file});return new Promise<void>((resolve,reject)=>{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function updatePhoto(photo:PhotoRecord){const db=await database();return new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).put(photo);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
export async function deletePhoto(id:string){const db=await database();return new Promise<void>((resolve,reject)=>{const request=db.transaction(STORE,'readwrite').objectStore(STORE).delete(id);request.onsuccess=()=>resolve();request.onerror=()=>reject(request.error)})}
export async function deleteReportPhotos(reportId:string){for(const photo of await photosFor(reportId))await deletePhoto(photo.id)}
export async function allPhotos():Promise<PhotoRecord[]>{const db=await database();return new Promise((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
